# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros
%define keepstatic 1

Name:       libsysperf
Summary:    Static helper library for CVS and proc file handling
Version:    0.2.4
Release:    1
Group:      Development/Tools
License:    GPLv2
URL:        git://gitorious.org/maemo-tools/libsysperf
Source0:    %{name}-v%{version}.tar.gz
Source100:  libsysperf.yaml
BuildRequires:  python


%description
Static helper library for CSV and /proc/ file handling, used by some sp-* tools


%package devel
Summary:    Header files for libsysperf
Group:      Development/Tools
Requires:   %{name} = %{version}-%{release}
Requires:   %{name} = %{version}

%description devel
Header files needed to build against libsysperf


%prep
%setup -q -n src

# >> setup
# << setup

%build
# >> build pre
# << build pre

# build gets done with make install

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
make install DESTDIR=%{buildroot}

# >> install post
# << install post









%files
%defattr(-,root,root,-)
%{_bindir}/sp_fix_tool_vers
%{_bindir}/sp_gen_changelog
%{_bindir}/sp_gen_manfile
%{_bindir}/sp_textconv
%{_libdir}/libsysperf.a
%{_mandir}/man1/sp_fix_tool_vers.1.gz
%{_mandir}/man1/sp_gen_changelog.1.gz
%{_mandir}/man1/sp_gen_manfile.1.gz
%{_mandir}/man1/sp_textconv.1.gz
# >> files
# << files


%files devel
%defattr(-,root,root,-)
%{_includedir}/libsysperf/argvec.h
%{_includedir}/libsysperf/array.h
%{_includedir}/libsysperf/calculator.h
%{_includedir}/libsysperf/cstring.h
%{_includedir}/libsysperf/csv_calc.h
%{_includedir}/libsysperf/csv_float.h
%{_includedir}/libsysperf/csv_table.h
%{_includedir}/libsysperf/hash.h
%{_includedir}/libsysperf/mem_pool.h
%{_includedir}/libsysperf/msg.h
%{_includedir}/libsysperf/proc_maps.h
%{_includedir}/libsysperf/proc_meminfo.h
%{_includedir}/libsysperf/proc_stat.h
%{_includedir}/libsysperf/proc_statm.h
%{_includedir}/libsysperf/proc_status.h
%{_includedir}/libsysperf/reader.h
%{_includedir}/libsysperf/release.h
%{_includedir}/libsysperf/str_array.h
%{_includedir}/libsysperf/str_pool.h
%{_includedir}/libsysperf/writer.h
%{_includedir}/libsysperf/xmalloc.h
%doc COPYING
# >> files devel
# << files devel

